title: Hui Liu (刘慧)
position: Associate Professor
affiliation: Shanghai University of International Business and Economics
email: liuh (at) suibe.edu.cn
keywords: hui liu
google_scholar: https://scholar.google.com/citations?user=lgQSEoIAAAAJ
github_link: 
linkedin: https://www.linkedin.com/in/hui-liu-a6a6a022
cv_link: 
univ_link: https://www.suibe.edu.cn/tsxy/2017/0530/c5782a45342/page.psp
avatar: ./assets/img/avatar_small1.png
google_analytics: 
favicon: ./assets/img/avatar.png
favicon_dark: ./assets/img/favicon-32x32.png
description: Hui Liu's Personal Webpage.
canonical: 
remote_theme: yaoyao-liu/strata-academic
