title: Hui Liu (刘慧)
position: Associate Professor
affiliation: Shanghai University of International Business and Economics
email: liuh (at) suibe.edu.cn
keywords: hui liu
google_scholar: https://scholar.google.com/citations?user=lgQSEoIAAAAJ
github_link: 
linkedin: 
cv_link: 
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Hui Liu's Personal Webpage.
canonical: 
remote_theme: yaoyao-liu/strata-academic
